package com.rifat.main;
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JList;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout.Group;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.GroupLayout;
import java.awt.Color;

public class test extends JFrame {

	public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        
        panel = new JPanel();
        panel.setBackground(new Color(102, 255, 102));
        GroupLayout gl_panel = new GroupLayout(panel);
        gl_panel.setHorizontalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 115, Short.MAX_VALUE)
        		.addGap(0, 115, Short.MAX_VALUE)
        );
        gl_panel.setVerticalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 49, Short.MAX_VALUE)
        		.addGap(0, 49, Short.MAX_VALUE)
        );
        panel.setLayout(gl_panel);
        
        JPanel jp[]=new JPanel[10];
        for(int c=0;c<10;c++)
        {
        	jp[c]=new JPanel();
        	jp[c].setBackground(new Color(102, 255, 102));
            GroupLayout gl = new GroupLayout(jp[c]);
            gl.setHorizontalGroup(
            	gl.createParallelGroup(Alignment.LEADING)
            		.addGap(0, 115, Short.MAX_VALUE)
            		.addGap(0, 115, Short.MAX_VALUE)
            );
            gl.setVerticalGroup(
            	gl_panel.createParallelGroup(Alignment.LEADING)
            		.addGap(0, 49, Short.MAX_VALUE)
            		.addGap(0, 49, Short.MAX_VALUE)
            );
            jp[c].setLayout(gl);
        	
        }
        
        
        
        

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        
        Group gph=jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addComponent(panel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE);
        
        
        for(int c=0;c<10;c++)
        {
        gph.addComponent(jp[c],GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE);
        }
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gph)
        			.addContainerGap(10, Short.MAX_VALUE))
        );
        
        
        
        
        Group gp=jPanel1Layout.createSequentialGroup()
    			.addGap(10)
    			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE);
    			
    			
    			
        
        gp.addGap(10);
        gp.addComponent(panel, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE);
        for(int c=0;c<10;c++)
        {
         gp.addGap(10);
         gp.addComponent(jp[c],GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE);
        }
        ((SequentialGroup) gp).addContainerGap(20, Short.MAX_VALUE);
        
        
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(gp)
        );
        
        
        
        jPanel1.setLayout(jPanel1Layout);

        jScrollPane1.setViewportView(jPanel1);
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(24)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 358, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(10, Short.MAX_VALUE))
        );
        
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private JPanel panel;
}
